
/*
Deployment script for db-pdi-staging

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;
GO


UPDATE [pdi_Publisher_Client] SET Notification_Email_Address = 'pdi_support@investorcom.com'
GO

PRINT N'Update complete.';
GO
