//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisher_Data_Operations_Tests.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PUB_Data_Integration_DEV {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PUB_Data_Integration_DEV() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Publisher_Data_Operations_Tests.Resources.PUB_Data_Integration_DEV", typeof(PUB_Data_Integration_DEV).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ArrayOfpdi_Client_Translation_Language&gt;
        ///  &lt;pdi_Client_Translation_Language&gt;
        ///    &lt;en-CA&gt;Adjustments&lt;/en-CA&gt;
        ///    &lt;fr-CA&gt;Ajustements&lt;/fr-CA&gt;
        ///  &lt;/pdi_Client_Translation_Language&gt;
        ///  &lt;pdi_Client_Translation_Language&gt;
        ///    &lt;en-CA&gt;As at March 31, 2021&lt;/en-CA&gt;
        ///    &lt;fr-CA&gt;Au 31 mars 2021&lt;/fr-CA&gt;
        ///  &lt;/pdi_Client_Translation_Language&gt;
        ///  &lt;pdi_Client_Translation_Language&gt;
        ///    &lt;en-CA&gt;As at March 31, 2021 , in thousands (except per share figures)&lt;/en-CA&gt;
        ///    &lt;fr-CA&gt;Au 31 mars 2021 in milliers (sauf les montants p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pdi_Client_Translation_Language {
            get {
                return ResourceManager.GetString("pdi_Client_Translation_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ArrayOfpdi_Data_Type_Merge_Table&gt;
        ///  &lt;pdi_Data_Type_Merge_Table&gt;
        ///    &lt;Field_Name_Prefix&gt;M15&lt;/Field_Name_Prefix&gt;
        ///    &lt;Check_Field_Row&gt;-1&lt;/Check_Field_Row&gt;
        ///    &lt;Check_Field_Column&gt;0&lt;/Check_Field_Column&gt;
        ///    &lt;Desired_Rows&gt;10&lt;/Desired_Rows&gt;
        ///    &lt;Interim_Indicator&gt;Sep&lt;/Interim_Indicator&gt;
        ///    &lt;Interim_Offset&gt;1&lt;/Interim_Offset&gt;
        ///  &lt;/pdi_Data_Type_Merge_Table&gt;
        ///  &lt;pdi_Data_Type_Merge_Table&gt;
        ///    &lt;Field_Name_Prefix&gt;M11&lt;/Field_Name_Prefix&gt;
        ///    &lt;Check_Field_Row&gt;2&lt;/Check_Field_Row&gt;
        ///    &lt;Check_Field_Column&gt;1&lt;/C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pdi_Data_Type_Merge_Table {
            get {
                return ResourceManager.GetString("pdi_Data_Type_Merge_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ArrayOfpdi_Global_Text_Language&gt;
        ///  &lt;pdi_Global_Text_Language&gt;
        ///    &lt;Scenario&gt;01&lt;/Scenario&gt;
        ///    &lt;en-CA&gt;January&lt;/en-CA&gt;
        ///    &lt;fr-CA&gt;janvier&lt;/fr-CA&gt;
        ///  &lt;/pdi_Global_Text_Language&gt;
        ///  &lt;pdi_Global_Text_Language&gt;
        ///    &lt;Scenario&gt;02&lt;/Scenario&gt;
        ///    &lt;en-CA&gt;February&lt;/en-CA&gt;
        ///    &lt;fr-CA&gt;février&lt;/fr-CA&gt;
        ///  &lt;/pdi_Global_Text_Language&gt;
        ///  &lt;pdi_Global_Text_Language&gt;
        ///    &lt;Scenario&gt;03&lt;/Scenario&gt;
        ///    &lt;en-CA&gt;March&lt;/en-CA&gt;
        ///    &lt;fr-CA&gt;mars&lt;/fr-CA&gt;
        ///  &lt;/pdi_Global_Text_Language&gt;
        ///  &lt;pdi_Global_Text_Language&gt;
        ///    &lt;Scenario [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pdi_Global_Text_Language {
            get {
                return ResourceManager.GetString("pdi_Global_Text_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;ArrayOfpdi_Publisher_Documents xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///	&lt;dbo.pdi_Publisher_Documents&gt;
        ///		&lt;Client_ID&gt;1002&lt;/Client_ID&gt;
        ///		&lt;Document_Type_ID&gt;5&lt;/Document_Type_ID&gt;
        ///		&lt;LOB_ID&gt;3&lt;/LOB_ID&gt;
        ///		&lt;Document_Number&gt;F013_ISF9&lt;/Document_Number&gt;
        ///		&lt;FundCode&gt;F013&lt;/FundCode&gt;
        ///		&lt;SeriesLetter&gt;JDSC&lt;/SeriesLetter&gt;
        ///		&lt;InceptionDate&gt;13/09/2021&lt;/InceptionDate&gt;
        ///		&lt;FFDocAgeStatusID&gt;2&lt;/FFDocAgeStatusID&gt;
        ///		&lt;IsActiveStatus&gt;1&lt;/IsActiveStatus&gt;
        ///	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pdi_Publisher_Documents {
            get {
                return ResourceManager.GetString("pdi_Publisher_Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;ArrayOfpdi_Publisher_Documents&gt;
        ///	&lt;pdi_Publisher_Documents&gt;
        ///		&lt;Document_Number&gt;111A&lt;/Document_Number&gt;
        ///		&lt;FundCode&gt;111&lt;/FundCode&gt;
        ///		&lt;SeriesLetter&gt;A&lt;/SeriesLetter&gt;
        ///		&lt;InceptionDate&gt;10/10/2020&lt;/InceptionDate&gt;
        ///		&lt;FFDocAgeStatus&gt;BrandNewFund&lt;/FFDocAgeStatus&gt;
        ///		&lt;AgeCalendarYears&gt;0&lt;/AgeCalendarYears&gt;
        ///		&lt;InDocuments&gt;0&lt;/InDocuments&gt;
        ///		&lt;Other_Change&gt;&lt;/Other_Change&gt;
        ///	&lt;/pdi_Publisher_Documents&gt;
        ///	&lt;pdi_Publisher_Documents&gt;
        ///		&lt;Document_Number&gt;111B&lt;/Document_Number&gt;
        ///		&lt;F [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pdi_Publisher_Documents_Results {
            get {
                return ResourceManager.GetString("pdi_Publisher_Documents_Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ArrayOfpub_Historic_Field_Data&gt;
        ///  &lt;a&gt;
        ///    &lt;FIELD_NAME&gt;M11a&lt;/FIELD_NAME&gt;
        ///    &lt;Content&gt;&amp;lt;table&amp;gt;&amp;lt;row&amp;gt;&amp;lt;cell&amp;gt;HSBC Canadian Bond Fund – Investor Series – Net Assets per Unit&amp;amp;lt;sup&amp;amp;gt;(1)&amp;amp;lt;/sup&amp;amp;gt;&amp;lt;/cell&amp;gt;&amp;lt;cell/&amp;gt;&amp;lt;cell/&amp;gt;&amp;lt;cell/&amp;gt;&amp;lt;cell/&amp;gt;&amp;lt;cell/&amp;gt;&amp;lt;/row&amp;gt;&amp;lt;row&amp;gt;&amp;lt;cell&amp;gt;Year(s) ended December 31&amp;lt;/cell&amp;gt;&amp;lt;cell/&amp;gt;&amp;lt;cell/&amp;gt;&amp;lt;cell/&amp;gt;&amp;lt;cell/&amp;gt;&amp;lt;cell/&amp;gt;&amp;lt;/row&amp;gt;&amp;lt;row&amp;gt;&amp;lt;cell/&amp;gt;&amp;lt;cell&amp;gt;2022&amp;lt;/cell&amp;gt;&amp; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pub_Historic_Field_Data {
            get {
                return ResourceManager.GetString("pub_Historic_Field_Data", resourceCulture);
            }
        }
    }
}
