CREATE TABLE [dbo].[pdi_Publisher_Documents] (
    [Client_ID]                        INT            NOT NULL,
    [Document_Type_ID]                 INT            NOT NULL,
    [LOB_ID]                           INT            NOT NULL,
    [Document_Number]                  NVARCHAR (50)  NOT NULL,
    [FundCode]                         NVARCHAR (50)  NOT NULL,
    [SeriesLetter]                     NVARCHAR (50)  NULL,
    [SeriesLetterFR]                   NVARCHAR (50)  NULL,
    [TickerSymbol]                     VARCHAR (50)   NULL,
    [Cusip]                            VARCHAR (50)   NULL,
    [InceptionDate]                    NVARCHAR (50)  NULL,
    [FFDocAgeStatusID]                 INT            NULL,
    [Is120ConsecutiveMonths]           BIT            NULL,
    [AgeCalendarYears]                 INT            NULL,
    [NegativeReturnCalendarYears]      INT            NULL,
    [IsProforma]                       BIT            NULL,
    [IsMERAvailable]                   BIT            NULL,
    [MerFeeWaiver]                     BIT            NULL,
    [Switching]                        BIT            NULL,
    [SwitchToSeries]                   NVARCHAR (50)  NULL,
    [IsConsolidated]                   BIT            NULL,
    [IsActiveStatus]                   BIT            NULL,
    [Date_Created]                     DATETIME       NULL,
    [FilingReferenceID]                NVARCHAR (50)  NULL,
    [Last_Filing_Date]                 NVARCHAR (50)  NULL,
    [Last_Updated]                     DATETIME       NULL,
    [IsUnderlying]                     BIT            NULL,
    [NoSecuritiesIssued]               BIT            NULL,
    [ProxySeriesLink]                  BIT            NULL,
    [ProxyStartEndYearEqual]           BIT            NULL,
    [PerformanceReset]                 BIT            NULL,
    [PerformanceResetDate]             NVARCHAR (50)  NULL,
    [IsPool]                           BIT            NULL,
    [IsUSD]                            BIT            NULL,
    [IsCorporateClass]                 BIT            NULL,
    [FundFamilyNameEN]                 NVARCHAR (500) NULL,
    [FundFamilyNameFR]                 NVARCHAR (500) NULL,
    [SeriesDesignationEN]              NVARCHAR (50)  NULL,
    [SeriesDesignationFR]              NVARCHAR (50)  NULL,
    [DisplaySeriesNameEN]              NVARCHAR (50)  NULL,
    [DisplaySeriesNameFR]              NVARCHAR (50)  NULL,
    [UnderlyingIndexNameEN]            NVARCHAR (50)  NULL,
    [UnderlyingIndexNameFR]            NVARCHAR (50)  NULL,
    [Document_FileName_EN]             VARCHAR (500)  NULL,
    [Document_FileName_FR]             VARCHAR (500)  NULL,
    [Sort_Order]                       INT            NULL,
    [PortfolioCharacteristicsTemplate] NVARCHAR (50)  NULL,
    CONSTRAINT [PK_pdi_Publisher_Documents_1] PRIMARY KEY CLUSTERED ([Client_ID] ASC, [Document_Type_ID] ASC, [LOB_ID] ASC, [Document_Number] ASC),
    CONSTRAINT [FK_pdi_Publisher_Documents_pdi_Document_Life_Cycle_Status] FOREIGN KEY ([FFDocAgeStatusID]) REFERENCES [dbo].[pdi_Document_Life_Cycle_Status] ([FFDocAgeStatusID]),
    CONSTRAINT [FK_pdi_Publisher_Documents_pdi_Document_Type] FOREIGN KEY ([Document_Type_ID]) REFERENCES [dbo].[pdi_Document_Type] ([Document_Type_ID]),
    CONSTRAINT [FK_pdi_Publisher_Documents_pdi_Line_of_Business] FOREIGN KEY ([LOB_ID]) REFERENCES [dbo].[pdi_Line_of_Business] ([LOB_ID]),
    CONSTRAINT [FK_pdi_Publisher_Documents_pdi_Publisher_Client] FOREIGN KEY ([Client_ID]) REFERENCES [dbo].[pdi_Publisher_Client] ([Client_ID])
);


GO
EXECUTE sp_addextendedproperty @name = N'sys_data_classification_recommendation_disabled', @value = 1, @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'pdi_Publisher_Documents', @level2type = N'COLUMN', @level2name = N'SwitchToSeries';

